name: Trigger auto deployment for simpletodoapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'frontend/**'
    - '.github/workflows/simpletodoapp-AutoDeployTrigger-4ac383c2-2c16-4907-976f-ecfa541bc455.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: simpletodoapp.azurecr.io
          username: ${{ secrets.SIMPLETODOAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.SIMPLETODOAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: simpletodoapp.azurecr.io/simpletodoapp:${{ github.sha }}
          file: ./frontend/Dockerfile
          context: ./frontend/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SIMPLETODOAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n simpletodoapp -g docker-java-event --server simpletodoapp.azurecr.io --username  ${{ secrets.SIMPLETODOAPP_REGISTRY_USERNAME }} --password ${{ secrets.SIMPLETODOAPP_REGISTRY_PASSWORD }}
            az containerapp update -n simpletodoapp -g docker-java-event --image simpletodoapp.azurecr.io/simpletodoapp:${{ github.sha }}
